### PR TITLE
fix: dynamic rowHeight is not updated when data/columns changed

### LINKED ISSUE #177: Inner grid width not recalculated after hiding columns in dynamic mode
tldr if you are using dynamic row heights and remove/hide a column, the inner grid width is not recalculated.

Repro steps:
1) clone this repo (https://github.com/jamesonhill/react-base-table-repro) and run `yarn && yarn start` 
2) Click the button to remove the first column
3) Horizontally scroll to the end of the grid

Expected:
1) Inner grid width is calculated and displays as total columns width

Actual:
1) Inner grid width still includes the width of the hidden column

This only seems to happen in dynamic mode. You can technically work around it by doing `        tableRef.current?.table?.bodyRef.resetAfterColumnIndex(0, false);`, however that's pretty hacky and should work out of the box.

### PR DESCRIPTION
**Pull request by nihgwu**
close #177 and also fixed some other issues

### CODE REVIEW

File: src/BaseTable.js [hunk 1]
```diff
@@ -98,8 +98,20 @@ class BaseTable extends React.PureComponent {
     });
     this._resetColumnManager = memoize((columns, fixed) => {
       this.columnManager.reset(columns, fixed);
+
+      if (this.props.estimatedRowHeight && fixed) {
+        this.resetColumnWidthCache(false);
```
Comment (nihgwu) [inline src/BaseTable.js:103]: @jamesonhill this way is much simpler, the memoize does the magic

Comment (jamesonhill) [reply src/BaseTable.js:103]: thank you so much!! I was about to report another issue where sorting in place does not resize the cells, but this looks to resolve that issue as well.

Comment (nihgwu) [reply src/BaseTable.js:103]: I should have tested the new feature in our internal advanced table, then I would find those issues earlier
