### PR TITLE
fix: regression of expansion with frozen columns

### LINKED ISSUE #179: Expanded Rows don't render before hover/scroll on 1.10.1
### Link to codesandbox:

[Edit React Tables](https://codesandbox.io/s/react-tables-x3vii?fontsize=14&hidenavigation=1&theme=dark)

### Bug:

When expanding rows the children rows don't render at first.
Then render on next hover / scroll.

Seems to be coming from the latest version as reverting to 1.9.4 avoids the problem.

Cheers !

### PR DESCRIPTION
**Pull request by nihgwu**
close #179

### CODE REVIEW

File: src/BaseTable.js [hunk 1]
```diff
@@ -168,31 +168,16 @@ class BaseTable extends React.PureComponent {
...
-  }
-
   /**
    * Get the total height of all rows, including expanded rows.
    */
   getTotalRowsHeight() {
     const { rowHeight, estimatedRowHeight } = this.props;
-    return this.table ? this.table.getTotalRowsHeight() : this._data.length * (estimatedRowHeight || rowHeight);
+
+    if (estimatedRowHeight) {
```
Comment (nihgwu) [inline src/BaseTable.js:177]: this is the only place without proper guard that cause the issue
