### PR TITLE
fix: getTotalRowsHeight could be different before/after render in dynamic mode

### LINKED ISSUE #199: Frozen columns can have incorrect height on initial render when using dynamic row heights
Frozen columns height are incorrect until the first grid re-render.

Example: https://autodesk.github.io/react-base-table/playground#MYewdgzgLgBKA2BXAtpGBeGBzApmHATgIZQ4DCISqEAFAIwAMAlAFCiSwAmJRG2ehEjgAiPGghSQANDACsrdtBgAzAiABeeUVF6Zc+YqW1FxlSRBl0ZAclUa8AWjUB3B9dZtwS5QEsAHjicFFRomBLUAHTIRAAONKYhMuFgAJJgnDh+TBgAfDAA3iwwMPA4sHaaYEUwPsowCZJpGX4wADwwdNkVeHzBkhEAYmqVwj4EOMBQPuARADIAogMAKtW19clNmTB5ABxdwz2YfaiDB2Cj45PTYBEASikA4gASK8XjUIgEYAUwEX-JMm63wAvixgR5FLBMjEiOljmAANI4ACefGsyQcDGsLBYAHpcTAiJxODAICBkDhSYgAEY1UjICAsZQgAj1UqwHx8BgAbhqbQ6DB5NQA1MLsoVitwdBEYogIAALGgS4q-P5SogAbQYAF0pNVij5OAAuGAAAwAJPl1VrtRFDcCHBAaQ5LT5gaa9SqYDDxmAoCljTBrTq7ZxPSqNdDYUEzKgkcjtSbTQBlGkwV3u8Pg6rqmVyxXK4p-CLWgBMuv1NUDFqtPA15dDDqd1Jd+TdHsrPrw-sDZdthvDxUjfhhcNjiJRibNqdpGY7xWzkp4eYVSsrxb7g6rSctfcbjudzdb7a3Xb9AZ3tZ09f7nCbzrnW+Ho5jIXjU5Tzpn6bbmeq2dBTwOBgKBxhEHg+EQMBlHgEhSDAGh1Q8aEWS4HBlCIRB4FgGhsnQPIaGqVoliIalSkrXwAk4StkggdB8kowJ4QgUEvXVejQJwcCdFYlUgWMej+J4XjiijMc3xReixNfSR4xEmAcGgHxolIThbhAZwnhwHwsHlKB6IAFgYXjcRyFhWCAA

When the above grid loads, you can see the grid border/box-shadow below the last row. Once you hover over any row or trigger a re-render in some other way, the columns re-size correctly.
Working on figuring out a fix.

### PR DESCRIPTION
**Pull request by nihgwu**
fix #199 

the bug also happens with `maxHeight`, the cause is that `getTotalRowsHeight` would be call before rendered, so the height is the previous value of `GridTable`

### CODE REVIEW

File: src/BaseTable.js [hunk 1]
```diff
@@ -739,6 +740,12 @@ class BaseTable extends React.PureComponent {
       this._maybeCallOnEndReached();
     }
     this._maybeScrollbarPresenceChange();
+
+    setTimeout(() => {
```
Comment (nihgwu) [inline src/BaseTable.js:744]: just don't understand why it should be wrapped with `setTimeout`, without it, we would still get the previous value lol

File: src/BaseTable.js [hunk 2]
```diff
@@ -739,6 +740,14 @@ class BaseTable extends React.PureComponent {
       this._maybeCallOnEndReached();
     }
     this._maybeScrollbarPresenceChange();
+
+    if (estimatedRowHeight) {
+      setTimeout(() => {
```
Comment (nihgwu) [inline src/BaseTable.js:745]: just don't understand why it should be wrapped with setTimeout, without it, we would still get the previous value lol

**Comment by nihgwu** [comment]
@jamesonhill FYI

File: src/BaseTable.js (hunk 2 above)
Comment (jamesonhill) [reply src/BaseTable.js:746]: I've seen this type of approach used before in some apps. In those cases it was used to ensure the calculation is run on the "next tick" (in nodejs terminology) or "next frame".

Comment (jamesonhill) [reply src/BaseTable.js:746]: It sort of emulates how `useEffect` in React 16.9 runs after initial render.

Comment (nihgwu) [reply src/BaseTable.js:746]: Yes I understand the mechanism, but I though the dom should has been updated on `componentDidUpdate`

Comment (nihgwu) [reply src/BaseTable.js:746]: Never mind, if you don't have any concern on this change I'm going to merge it

Comment (nihgwu) [reply src/BaseTable.js:746]: OK I understand now, after row heights measured, we reset the inner components directly instead of update the table itself, so `componentDidUpdate` won't be invoked after that
image

File: src/BaseTable.js [hunk 3]
```diff
@@ -742,7 +742,9 @@ class BaseTable extends React.PureComponent {
     this._maybeScrollbarPresenceChange();
 
     if (estimatedRowHeight) {
-      // have to wrap with setTimeout or we would still get the previous value
+      // we have to wrap with setTimeout or we would still get the previous value,
+      // as we reset the inner components directly instead of update the table itself after row heights measured,
```
Comment (nihgwu) [inline src/BaseTable.js:746]: I updated the comments here, another option is we call `forceUpdate` after `forceUpdateTable` https://github.com/Autodesk/react-base-table/blob/master/src/BaseTable.js#L127，which would more consistent as `componentDidUpdate` should be invoked after the layout changed, then we could remove the setTimeout wrapper here, WDYT @jamesonhill

Comment (nihgwu) [reply src/BaseTable.js:746]: OK never mind again, the current solution is better, as if the totalRowsHeight doesn't change, we don't need call `cDU`, but if it does, it will be invoked after timeout

Comment (jamesonhill) [reply src/BaseTable.js:746]: Yea i like the current solution over calling `forceUpdate` to avoid un-necessary work.
